### ISSUE TITLE
JS example using CryptoJS

### ISSUE THREAD

**Issue by ColdFire87** [hydrogen18/schnellburger#1]
Hi Eric,

I'm trying to use your library in a project to secure an API and I'm using Postman (https://www.getpostman.com/) to issue the requests. Within Postman I can use CryptoJS to create the Authorization header in a pre-request script:

```JavaScript
var client_id = 123;
var secret = 'my_secret';

var method = request.method;
var url = postman.getEnvironmentVariable('url');
var port = postman.getEnvironmentVariable('port');
var reqUri = request.url.replace(/{{url}}/, url).replace(/{{port}}/, port);
var encodedUri = encodeURIComponent(reqUri).toLowerCase();
var requestBody = request.data;


var rawSignature = method + encodedUri + requestBody;
var signature = CryptoJS.HmacSHA256(rawSignature, secret);
signature = client_id + signature

var words = CryptoJS.enc.Utf8.parse(signature);
var b64Signature = CryptoJS.enc.Base64.stringify(words).toString();

postman.setEnvironmentVariable('signature', b64Signature);
```

The signature I get out is
`12380510a00825cdf3f20aa67bc4709b9a579faf10bd4cc134e9bdccb5aed7c2095`

and the b64Signature is
`MTIzODA1MTBhMDA4MjVjZGYzZjIwYWE2N2JjNDcwOWI5YTU3OWZhZjEwYmQ0Y2MxMzRlOWJkY2NiNWFlZDdjMjA5NQ==`

I get back the following error: 
```
Key Index Wrong Length
---
The key index at the beginning of the authorization bytes must be exactly 0,2,4, or 8 bytes representing an unsigned integer
```

My Go code is:
```Go
package auth

import (
    "crypto/sha256"

    "github.com/hydrogen18/schnellburger"
)

//Simple implementation of key provider
type DictKeyProvider map[uint64][]byte

func (dkp DictKeyProvider) GetKey(index uint64) ([]byte, error) {
    k, ok := dkp[index]
    if !ok {
        return nil, nil
    }
    return k, nil
}

//Create an instance of Schnellburger
var SB schnellburger.Schnellburger

func init() {
    kp := DictKeyProvider{}

    //Configure keys
    // kp[0] = []byte{0x1, 0x2, 0x3, 0x4}
    kp[123] = []byte("my_secret");

    //Use the SHA256 hash
    SB.Algorithm = sha256.New
    //Use the dictionary key provider
    SB.Kp = kp
}
```

I managed to pinpoint the issue by using some print statemets in the `FindHmacHeader` function in `schnellburger.go`:

```Go
//The header contains either
// no index - use a value of 0
// 2 byte unsigned integer
// 4 byte unsigned integer
// 8 byte unsigned integer
//
//If one of these conditions is not satisfied,
//fail
keyBytesLength := len(headerBinary) - sb.algorithmSize

log.Println("sb.algorithmSize -> ", sb.algorithmSize)
log.Println("headerBinary -> ", len(headerBinary))
log.Println("keyBytesLength -> ", keyBytesLength)
```

And the output I get is:
```
2017/02/20 16:55:55 sb.algorithmSize ->  32
2017/02/20 16:55:55 headerBinary ->  67
2017/02/20 16:55:55 keyBytesLength ->  35
```

In the Postman script if I comment out the line `signature = client_id + signature` then I get an output of:
```
2017/02/20 16:56:16 sb.algorithmSize ->  32
2017/02/20 16:56:16 headerBinary ->  64
2017/02/20 16:56:16 keyBytesLength ->  32
```

This basically says the `client_id` takes up 3bytes (one per character).
The disturbing fact is that the expected algorithm size is 32 while the header size is 64.

Any help would be much appreciated!
Thank you!

**Comment by hydrogen18** [comment]
You've base64 encoded a hexadecimal string in your javascript. This is not part of the API's requirements nor does it understand it

Here is what your "signature" looks like after decoding to the Go code.

```
>>> print base64.b64decode('MTIzODA1MTBhMDA4MjVjZGYzZjIwYWE2N2JjNDcwOWI5YTU3OWZhZjEwYmQ0Y2MxMzRlOWJkY2NiNWFlZDdjMjA5NQ==')
12380510a00825cdf3f20aa67bc4709b9a579faf10bd4cc134e9bdccb5aed7c2095
```

**Comment by ColdFire87** [comment]
I followed the documentation at [https://godoc.org/github.com/hydrogen18/schnellburger](https://godoc.org/github.com/hydrogen18/schnellburger) which says 

> The Authorization header is base64 encoded by the client. The server decodes this and uses the resulting byte slice as follows

If I don't base64 encode the signature and send it in the Authorization header as it is (from `var signature = CryptoJS.HmacSHA256(rawSignature, secret);` the results ends up being

```
2017/02/20 17:36:52 sb.algorithmSize ->  32
2017/02/20 17:36:52 headerBinary ->  48
2017/02/20 17:36:52 keyBytesLength ->  16
```

So the signature is 48 bytes long. Any thoughts on this?

**Comment by hydrogen18** [comment]
There is no way that removing the base64 encoding could fix the problem you are encountering.

My guess is `var words = CryptoJS.enc.Utf8.parse(signature);` is converting to hexadecimal encoding.

**Comment by hydrogen18** [comment]
Closed due to lack of feedback from author.
